import type { CelestialObject, CommunityReport } from "./types";

export const CELESTIAL_OBJECTS: CelestialObject[] = [
  {
    // invisible from most of contiguous US
    ObjectID: 1,
    Name: "Acrux",
    ObjectCategory: "Triple Star",
    Constellation: "Crux",
    Magnitude: 0.76,
    RightAscension: 186.6495634,
    Declination: -63.0991,
  },
  {
    ObjectID: 31,
    Name: "Andromeda Galaxy",
    ObjectCategory: "Galaxy",
    Constellation: "Andromeda",
    Magnitude: 3.44,
    RightAscension: 10.68,
    Declination: 41.266667,
  },
  {
    ObjectID: 42,
    Name: "Orion Nebula",
    ObjectCategory: "Planetary Nebula",
    Constellation: "Orion",
    Magnitude: 4.0,
    RightAscension: 83.82,
    Declination: -5.383333,
  },
  {
    ObjectID: 45,
    Name: "Pleiades",
    ObjectCategory: "Open Cluster",
    Constellation: "Taurus",
    Magnitude: 1.6,
    RightAscension: 56.85,
    Declination: 24.116667,
  },
  {
    ObjectID: 13,
    Name: "Hercules Cluster",
    ObjectCategory: "Globular Cluster",
    Constellation: "Hercules",
    Magnitude: 5.8,
    RightAscension: 250.42,
    Declination: 36.45,
  },
  {
    ObjectID: 57,
    Name: "Ring Nebula",
    ObjectCategory: "Reflection Nebula",
    Constellation: "Lyra",
    Magnitude: 8.8,
    RightAscension: 283.40,
    Declination: 33.016667,
  },
  {
    ObjectID: 51,
    Name: "Whirlpool Galaxy",
    ObjectCategory: "Galaxy",
    Constellation: "Canes Venatici",
    Magnitude: 8.4,
    RightAscension: 202.47,
    Declination: 47.183333,
  },
  {
    ObjectID: 2,
    Name: "Crab Nebula",
    ObjectCategory: "Reflection Nebula",
    Constellation: "Taurus",
    Magnitude: 8.4,
    RightAscension: 83.63,
    Declination: 22,
  },
  {
    ObjectID: 3,
    Name: "Sirius",
    ObjectCategory: "Star",
    Constellation: "Canis Major",
    Magnitude: -1.46,
    RightAscension: 101.29,
    Declination: 16.7,
  },
  {
    ObjectID: 4,
    Name: "Vega",
    ObjectCategory: "Star",
    Constellation: "Lyra",
    Magnitude: 0.03,
    RightAscension: 279.23,
    Declination: 38.47,
  },
  {
    // circumpolar from contiguous US
    ObjectID: 81,
    Name: "Bode's Galaxy",
    ObjectCategory: "Galaxy",
    Constellation: "Ursa Major",
    Magnitude: 6.94,
    RightAscension: 148.89,
    Declination: 69.03,
  },
  {
    ObjectID: 104,
    Name: "Sombrero Galaxy",
    ObjectCategory: "Galaxy",
    Constellation: "Virgo",
    Magnitude: 8.0,
    RightAscension: 190.00,
    Declination: -11.37,
  },
  {
    ObjectID: 27,
    Name: "Dumbbell Nebula",
    ObjectCategory: "Planetary Nebula",
    Constellation: "Vulpecula",
    Magnitude: 7.5,
    RightAscension: 299.90,
    Declination: 22.43,
  },
  {
    ObjectID: 5,
    Name: "Albireo",
    ObjectCategory: "Double Star",
    Constellation: "Cygnus",
    Magnitude: 3.18,
    RightAscension: 292.68,
    Declination: 27.57,
  },
  {
    ObjectID: 8,
    Name: "Lagoon Nebula",
    ObjectCategory: "Reflection Nebula",
    Constellation: "Sagittarius",
    Magnitude: 6.0,
    RightAscension: 270.90,
    Declination: -24.23,
  },
  {
    ObjectID: 44,
    Name: "Beehive Cluster",
    ObjectCategory: "Globular Cluster",
    Constellation: "Cancer",
    Magnitude: 3.7,
    RightAscension: 130.10,
    Declination: 19.59,
  },
  {
    ObjectID: 64,
    Name: "Black Eye Galaxy",
    ObjectCategory: "Galaxy",
    Constellation: "Coma Berenices",
    Magnitude: 8.52,
    RightAscension: 194.18,
    Declination: 21.41,
  },
];

export const COMMUNITY_REPORTS: CommunityReport[] = [
  {
    ReportID: 1,
    UserID: 1,
    UserName: "Clara Voss",
    Latitude: 41.66384,
    Longitude: -77.82321,
    CreatedAt: "Thu, 15 Jan 2026 21:30:00 GMT",
    ReportText: "Outstanding night at Cherry Springs. Milky Way was incredibly detailed — could resolve individual star clouds in Sagittarius with the naked eye. M13 was breathtaking in the 10\" dob. Light dome from Coudersport barely visible.",
  },
  {
    ReportID: 2,
    UserID: 2,
    UserName: "David Nakamura",
    Latitude: 32.443417,
    Longitude: -110.788124,
    CreatedAt: "Mon, 15 Sep 2025 22:30:00 GMT",
    ReportText: "Monsoon season approaching but still had a great session. Seeing was exceptional — planetary detail on Saturn was the best I've seen this year. Ring shadow clearly visible. Transparency dropped near midnight with some high cirrus.",
  },
  {
    ReportID: 3,
    UserID: 3,
    UserName: "Mei-Lin Zhao",
    Latitude: 36.27,
    Longitude: 116.51,
    CreatedAt: "Fri, 05 Dec 2025 22:30:00 GMT",
    ReportText: "Bortle 1 skies as promised. Airglow was stunning — visible as a faint greenish glow on the horizon. Zodiacal light was prominent. Brought my 4\" refractor and had fantastic wide-field views of Scorpius region. M6 and M7 were spectacular.",
  },
  {
    ReportID: 4,
    UserID: 4,
    UserName: "Tom Eriksen",
    Latitude: 51.1336,
    Longitude: -3.7525,
    CreatedAt: "Sun, 24 Aug 2025 22:00:00 GMT",
    ReportText: "Managed two hours before clouds rolled in. Seeing was poor due to jet stream — stars were twinkling significantly. Good for deep sky but planetary detail was poor. Caught the Virgo Galaxy Cluster before clouds covered the south.",
  },
  {
    ReportID: 5,
    UserID: 5,
    UserName: "Anika Patel",
    Latitude: 29.2500,
    Longitude: -103.2500,
    CreatedAt: "Thu, 30 Oct 2025 21:30:00 GMT",
    ReportText: "New moon weekend and Big Bend delivered. No wind all night, temps stayed comfortable. Spent the session on galaxies in Virgo. M87 jet was just detectable in the 12\" at high power. Sqm reading: 21.8 mag/arcsec².",
  },
];
